run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: unexported-return
      - name: error-return
      - name: error-strings
      - name: package-comments
        disabled: true
